language: go

sudo: required

os:
  - linux

go:
  - 1.14.x

env:
  - NODE_VERSION="0.12"

before_install:
  - nvm install $NODE_VERSION
  - ln -s /home/travis/.nvm/versions/node/v0.12.18/include/node /usr/local/include/node

addons:
  chrome: stable

services:
  - xvfb

install:
  - go get github.com/benitogf/katamari
  - npm install

script:
  - npm test