language: go

os:
  - linux

go:
  - 1.14.x

before_install:
  - npm i -g npm

addons:
  chrome: stable

services:
  - xvfb

install:
  - go get github.com/benitogf/katamari
  - npm install

script:
  - npm test