language: go
os:
  - linux

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

go:
  - 1.11.x

before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - go get github.com/benitogf/samo
  - npm install -g http-server
  - npm install

before_script:
  - npm run build

script:
  - nohup go run main.go
  - nohup http-server
  - sleep 3
  - npm test