language: go
os:
  - linux

go:
  - 1.11.x

addons:
  chrome: stable

services:
  - xvfb

install:
  - go get github.com/benitogf/samo
  - npm install -g http-server
  - npm install

before_script:
  - npm run build

script:
  - nohup go run main.go &
  - nohup http-server &
  - sleep 5
  - npm test