language: go
os:
  - linux

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

go:
  - 1.11.x

services:
  - xvfb

install:
  - go get github.com/benitogf/samo
  - npm install -g http-server
  - npm install

before_script:
  - npm run build

script:
  - nohup go run main.go &
  - nohup http-server &
  - sleep 5
  - npm test