language: go

os:
  - linux

go:
  - 1.14.x

env:
  - NODE_VERSION="0.11"

before_install:
  - nvm install $NODE_VERSION

addons:
  chrome: stable

services:
  - xvfb

install:
  - go get github.com/benitogf/katamari
  - npm install

script:
  - npm test